name: cvpr2022_env
channels:
- https://conda.anaconda.org/menpo
- conda-forge
dependencies:
- python==3.7
- openmpi
- openexr-python
- pip
- pip:
  - timm==0.4.12
  - torch==1.6.0
  - torchvision==0.7.0
  - wandb==0.10.12
  - webdataset==0.1.62
  - certifi==2021.10.8
  - ctypes-callable==1.0.4
  - cycler==0.11.0
  - fonttools==4.28.5
  - glfw==2.5.0
  - kiwisolver==1.3.2
  - matplotlib==3.5.1
  - numpy==1.21.5
  - opencv-python==4.5.5.62
  - packaging==21.3
  - Pillow==9.0.0
  - plydata==0.4.3
  - plyfile==0.7.4
  - protobuf==3.20
  - PyGLM==2.5.7
  - PyOpenGL==3.1.5
  - PyOpenGL-accelerate==3.1.5
  - pyparsing==3.0.6
  - PySDL2==0.9.10
  - pysdl2-dll==2.0.18
  - python-dateutil==2.8.2
  - pytz==2021.3
  - six==1.16.0
  - tqdm==4.62.3
  - open3d==0.9.0
  - noise==1.2.2